Generalized Resolver (#970)
* WIP generic resolver

* implemented dynamic resolve

* implemented a few resolver methods

* improvements

* improvements

* Clippy fixes

* fixed clippy

* Added documentation

* implemented default

* Added documentation

* Improved documentation

* Added resolve_core method

* moved into_any

* removed resolve_core

* started considering alternative approach

* Made into_delegate work

* refactored resolver

* started new experiment avoiding impl ValidatorDocument for boxed trait obj

* Introduced ValidatorBorrow

* Simplified API

* Fixed lints

* renamed trait

* Initial port of Resolver tests

* renamed variables in test

* Tested one more case

* Started building serious test suite

* fixed test

* Fixed clippy

* Some more tests

* removed test

* Moved resolver to new crate

* Added exposed internals under feature flag

* Started work on supporting multiple clients attached to the same method

* Started work on bindings

* fixes

* Fixed compilation error

* small changes

* Added very minimal wrapper around CoreDocument

* Added resolve method

* take functions by reference

* Got a working TS example

* reverted to using a single handler per method

* started refactor to passing functions in Rust

* Adapted tests to async closures

* refactored error

* started error handling improvements

* improved errors

* improved errors

* removed leftover TODOs

* Made Resolver Send + Sync (need to reconsider design for the bindings)

* started work on making the resolver agnostic with regards to threads

* re-export the Resolver type instead

* started command refactor

* renamed field

* removed Casting error variant

* removed unused import

* Added ThreadSafeValidatorDocument trait

* continued refactor to also support the single threaded scenario. Will finish this tomorrow morning

* Fixed bindings

* doc tests

* removed internals flag

* started cleaning up the commands module

* cleaned up the commands module

* improved documentation

* documented the error

* fixed documentation

* improved docs

* Removed BorrowValidator

* improved documentation

* fixed tests

* fixed tests

* Fixed bindings

* fixed documentation

* added missing handler tests

* more tests

* fixes

* fixed tests

* added failure tests

* removed duplicated code in tests

* removed internal method

* simplified tests

* refactored error

* added send sync assertion

* moved and improved send sync tests

* moved tests

* restrict parameters for better inference

* Fix workspace setup

* Added tests for the happy path

* tested concrete resolver in failure tests as well

* removed badly ported tests

* changed name of Error::cause

* Added new method and fixed error

* Remove superfluous `Sync` bound on `Future`s

* Added verify_presentation

* Add convenience method `attach_iota_handler`

* Added constructor

* fixed bindings

* improved typescript definitions

* Fixed type conversion

* Removed redundant code

* fixed tests. TODO: remove changes

* removed code

* made test more data oriented

* made handler errors more flexible

* serialized test input

* started extending the wasm constructor

* Finished the api for the bindings

* wasm bindings for CoreDocument

* pin tokio version

* fix format issue in Cargo.toml

* fix format issue in Cargo.toml

* fixed clippy warnings

* fix doc generating issue

* conditionally compile iota-client with features in identity_iota_client

* removed unnecessary declarations

* unpin tokio version

* fixed bindings

* merged feat/core_document_bindings

* fixed documentation

* Fixed clippy warnings

* Documented MixedResolver

* Moved position of annotation

* Simplified construction

* renamed tests

* started writing tests for the bindings

* testing the test

* started test

* improved tests

* completed JS tests

* fixed clippy lints in tests

* Made handler attachment consistent in the bindings

* Removed testing example

* removed deleted example for the README

* fixed omitted documentation

* Update identity_credential/src/validator/validator_document.rs

Co-authored-by: Philipp <philipp.gackstatter@iota.org>

* Update identity_credential/src/validator/validator_document.rs

Co-authored-by: Philipp <philipp.gackstatter@iota.org>

* Update identity_resolver/src/error.rs

Co-authored-by: Philipp <philipp.gackstatter@iota.org>

* addressed review comments

* deleted leftover files

* Clarify iota handler comment in Wasm

* Annotate types; add whitespace for readability

* Document `MixedResolver::resolve`

* Add whitespace for readability in tests

* Improve error message

* Remove unnecessary `Sync` bound on `DID` parameter

* Remove unnecessary `Send` & `Sync` bounds

* Impl `Debug` for `Resolver`

* Reexport resolver from `identity_iota`

* Regenerate api-reference

* Remove another `Send` bound

* improve resolver TS test

Co-authored-by: PhilippGackstatter <philipp.gackstatter@iota.org>
Co-authored-by: Abdulrahim Al Methiab <abdulrahim.almethiab@iota.org>